# Generated by Django 5.0.6 on 2024-07-11 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nutritionalinformation',
            name='food_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_info', to='tracker.foodentry'),
        ),
    ]
